module tb;
reg [3:0]a,b;
reg cin;
wire [3:0]sum;
wire cout;
ripple_carry_adder uut(.a(a),.b(b),.cin(cin),.sum(sum),.cout(cout));
initial begin
$dumpfile("wave.vcd");
$dumpvars(0,tb);
$display("\tA\tB\tCin\t|\tSUM\tCout");
$monitor("\t%b\t%b\t%b\t%b\t%b",a,b,cin,sum,cout);
a=4'b0000;b=4'b0000;cin=0;#10;
a=4'b0101;b=4'b1010;cin=0;#10;
a=4'b1011;b=4'b1111;cin=1;#10;
a=4'b1111;b=4'b1111;cin=1;#10;
$finish;
end
endmodule
